### PR TITLE
Change c_ prefix to hitsumabushi_ for emulated C syscalls

### PR DESCRIPTION
**Pull request by samhocevar**

### CODE REVIEW

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Review by hajimehoshi — CHANGES_REQUESTED** [review]
Sorry, can we do the same thing for 1.18_linux?

**Comment by samhocevar** [comment]
> Sorry, can we do the same thing for 1.18_linux?

Done!

**Review by hajimehoshi — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
